### ISSUE TITLE
Dev requested 

### ISSUE THREAD

**Issue by DeadneM** [PaperAirplane-Dev-Team/SwipeBack#10]
Hi i just want to check if the dev is still there 

App is working on on android 5.x but seems to have problem with 6.x 

 I can be a beta tester and some guy on XDA too

**Comment by PeterCxy** [comment]
I am the dev but for now I have no time debugging Xposed modules as I am preparing for Gaokao (a big exam) in June. I may get back after that.

**Comment by DeadneM** [comment]
Thanks for answering so fast! 
Ok happy to hear that 

Good luck for your exam!

**Comment by Harry-Chen** [comment]
@PeterCxy It will be a long time till June and Android N might be released till then. Thank you for your support and you may be able to test our new version on Android N as well LOL.😂
BTW I am just a bug creator but Peter is the guy who writes real code.😂

**Comment by DeadneM** [comment]
Lol yes that's true android N might be released but this module is still one those who made me install xposed 
The swipeback is a killer feature and i hope it never die 

 nice to see devs are still there 

I love catching bugs and now i have a name to put it on ^^

**Comment by linhphi9x94** [comment]
Transition effect bug on CM13 . Plz update for MM Bro
